export AGENT_ID

deploy-agent-network:
	$(MAKE) -C aws/agent-network deploy-agent-network

bootstrap-agent-vm:
	$(MAKE) -C aws/agent-vms bootstrap-agent-vm 

destroy-agent-vm:
	$(MAKE) -C aws/agent-vms destroy-agent-vm
